### ISSUE TITLE
New Role: The Plague Host & Pestilence (Own Team/Neutral Role)

### ISSUE THREAD

**Issue by Lunethia** [TTT-2/addon-ideas#1]
### The Plague Host

**Description** He's infected with the plague and the plague is spreading rapidly throughout the terrorist organization, can it be stopped before a certain Plague Overlord notices the disaster that is on the horizon?

**Alignment and win condition** The Plague Host is not aligned with anyone and on his own team. He does not have a winning condition, however he has a goal which is infecting every living player with the plague.

**Gameplay and Abilities**

**Shop** No, he will not have a shop by default.

- The Plague Host will need to infect every living player with the plague and he has multiple means to do so.

   1. He can place phials with infected liquid which explode whenever another player gets too close to them. The phials can also be destroyed from range, which will also trigger the explosion but must not infect anyone if nobody is close enough to it's radius.

   2. He can lay down dead bodies, which are infected with the plague. If anyone gets to close to an infected body, the plague will infect that player.

   3. If the Plague Host is able to kill someone, the body of his victim will also be infected with the plague.

   4. If an infected player dies, their body will remain infected and share the same infectious trades as the bodies placed by the Plague Host.

- The Plague Host will not be able to pick up weapons or ammunition, however he will start with a random loadout containing a primary and secondary weapon at round start.

-----

### Pestilence, Horseman of the Apocalypse

Or just Pestilence, for short.

**Description**  Pestilence is an immortal being send to the world to spread disease and gather the souls of anyone infected by it.

**Alignment and win condition** Pestilence is on his own team and will win once he is the last player alive.

**Gameplay and Abilities**

**Shop** No, he will not have a shop by default.

- Once every **living** player has been infected with the plague, the Plague Host will transform into Pestilence and from that point onwards receive a win condition and several buffs. But the player will also be revealed as Pestilence to everyone in the round.

- The transformation will be announced 10 seconds in advance for the Plague Host and to every player once he transformed. 

- Once transformed into Pestilence, the player can pick up any weapon and ammunition they want.

- Pestilence will receive a buff to his max HP, setting it to (200), armour (?) minimum and will be immune to most non-weapon damage. He will also receive a Radar.

- Pestilence will be stronger the more players are alive at the time he transforms. Giving him additional HP against more enemies.

- Optionally a custom player model could be implemented.

**Plays best With**

- A large group of innocents to take him on.
Which would suggest roles such as the survivalist, the priest, the spy, the occultist and additional detective roles.
- As well as different factions that may temporarily join forces to take on Pestilence, such as the Jackal, Necromancer or Serial Killer.

**Comment by Histalek** [comment]
i feel like this has at least some kind of similarity with [this Role idea](https://github.com/TTT-2/addon-ideas/issues/8). maybe there is some way to combine them (or not)

**Comment by Lunethia** [comment]
Hmm, well, I've read through the other role and agree that it might appear similar if you read about it hastily. But it really isn't. The only thing both roles have in common is, that at some point both go through a transformation, or, to put it in other terms, are upgraded to a stronger role.

But the differences are pretty clear in flavour and gameplay.
The possesed doesn't actually want to transform, as he dies of guilt and so on.
The PLague Lord actively does something to transform, instead of having to wait it out. 
I'm not trying to talk down anothers ideas, but I think this role might overall be more interesting to play, as it features a little more than just the transformation. Though that's really jsut my opinion, and as the "maker" of this roles' idea I'm decently biased anyway.
But I hope I could convey how both roles are not really easy to compare, as they play very differently.

**Comment by Pythagorion** [comment]
And the fact is: The PL and Pestilence are very advanced in concept phase. If both Roles PL and Possessed are too similar, I´d go with Pestilence. Playing the Waiting game in TTT was never the best strategy.

**Comment by Lunethia** [comment]
I think more action based, or at least something-to-do-in-the-meantime based gameplay is better for TTT! I don't want to hear people getting a role saying "aww not this role again". That's what you hear when people become innocent. :p

**Comment by Pythagorion** [comment]
indeed. This would be very sad for the coder who put effort into the role and then just hear how boring his role is.

**Comment by Pythagorion** [comment]
also. What happens when the PL is dead and all players get infected? Is Pestlience arriving or not? I´d say no, because it´s too strong, but we should discuss bout it

**Comment by Pythagorion** [comment]
Furthermore: What happens to the phioles and fake bodies? Will they disappear when PL dies?

**Comment by Lunethia** [comment]
If the Plague Lord dies then he will remain dead. The point is that you can try to take him out early.

**Comment by Pythagorion** [comment]
And his equipment shall disappear so that the non-infected bodies remain?

**Comment by Lunethia** [comment]
About the phioles, we could make them disappear, yes, but why bother lol.
I think I'd let that decision be of the one who's going to code it, because I still can't, as it's a lot of additional work.

**Comment by Pythagorion** [comment]
I know. And it will be my work when the lion is finished. ;D

**Comment by Lunethia** [comment]
I don't think his equipment should be pickupable.
I wonder what we do if somehow a new PL arises

**Comment by Lunethia** [comment]
I've finished remaking the issue. Should I delete this one and open a new onewith it since it is vastly different and the comments dont really make sense/are already implemented in the new version??

**Comment by TimGoll** [comment]
no, I think you should keep this one

**Comment by Lunethia** [comment]
Is there anything that I forgot in this "final" version of the submission?
If so, please ask, or point it out. :)

**Comment by Lunethia** [comment]
Had a suggestion by someone else to also give the plague host an infection gun. Probably a one shot no damage item to infect one player only with the plague. This was suggested as it can be very difficult for the plague host to get going on very large scale maps and with big playercount and also people with a more reserved and passive playstyle (fuck campers :p). If all these things come together I can see how the current ways of infection might not be enough.

**Comment by Alf21** [comment]
Moved to https://github.com/TTT-2/TTT2/discussions/760.
