### ISSUE TITLE
New Role: Armor Supplier 

### ISSUE THREAD

**Issue by Histalek** [TTT-2/addon-ideas#15]
* once the Armor System is in place a role that supplies armor to players could be nice

* current ideas:
  * 'Rook'-like (Rainbow6Siege Operator), place a stationary 'armor-station' which upon interacting gives the interacting player armor once
  * 'Torbjörn'-like (Overwatch Character), throws an entity which upon contact with a player gives the player armor

**Comment by Alf21** [comment]
Moved to https://github.com/TTT-2/TTT2/discussions/757.
