### ISSUE TITLE
A new helmet for new roles

### ISSUE THREAD

**Issue by dok441** [TTT-2/addon-ideas#18]
https://github.com/Facepunch/garrysmod/pull/1040
Предлагаю взять отсюда идею, шлема для роли hitman. Hitman сложная довольно роль для игрока и шлем как дополнительная защита от моментального убийство в голову будет очень даже хорошо.

**Comment by Alf21** [comment]
Moved to https://github.com/TTT-2/TTT2/discussions/747.
