### ISSUE TITLE
New ROLE Retribution

### ISSUE THREAD

**Issue by Paddy91088** [TTT-2/addon-ideas#23]
Ich hätte da eine Idee für eine Rolle , ich versuche zurzeit eine Möglichkeit ohne Karma auf dem Server zu spielen, jedoch die Spieler trotzdem zu hindern andere Mitspieler einfach aus Spaß zu killen. Die "Vergelter" Rolle müsste so aussehen, Sie wird gespielt im Team der Innocents, darf aber nicht getötet werden vom eigenen Team. Falls dies doch passiert, respawnt der Spieler im Gegnerischen Team. Der Vergelter dürfte erst entarnt werden wenn er getötet wird, er selbst und andere Spieler dürfen nicht wissen wer der Vergelter ist. Somit könnte man Spieler bestrafen ohne ein Karma System. Ich habe die Idee von der Rolle "The Unknown" bekommen. Informiert mich bitte falls ihr mal sowas plant !

**Comment by TimGoll** [comment]
Nicht ganz das was du suchst, aber hast du dir mal die verschiedenen Jester States angeschaut?

**Comment by Paddy91088** [comment]
damit kann ich vllt was anfangen , State 1 könnte die sache schon erledigen . Sehen die Teammitglieder wer der Jester ist?

**Comment by TimGoll** [comment]
ich glaube Ts sehen wer der Jester ist, sonst niemand. Bin mir da aber auch nicht 100% sicher

**Comment by Paddy91088** [comment]
okay ich werds mal ansprechen in unserer Gruppe mit den Leuten , vllt ergibt sich da ja was .

**Comment by Paddy91088** [comment]
So hab ich das mal für uns auf dem Server eingestellt und den Leuten erklärt.

Der Jester taucht erst auf wenn eine Spielerzahl von 9 erreicht wird.
Damit sind 3 Traitor , 4 Innocent, 1 Detektiv und 1 Jester im Spiel.
Der Jester spielt in seinem eigenen Team und es ist sein Ziel, von jemandem getötet zu werden.
Niemand ausser der Traitor sieht wer in der Gruppe der Jester ist.
Der Jester verursacht keinen Schaden an anderen Spielern. Somit soll er nur Unruhe ins Spiel bringen und die Leute nervös machen.( "Hey, auf mich wurde geschossen!")
Wenn der Jester getötet wird , können mehrere "Winstates" ausgelöst werden , diese Bedingung kann man Serverseitig einstellen.

In Unserem Falle ist eingestellt:
Der Innocent stirbt wenn der Jester getötet wird , der Jester kann weiter leben.
Die Traitor haben es nun schwerer, tötet einer ausversehen den Jester, stirbt der Traitor auch .
Somit ist mehr Fingerspitzengefühl gefragt als Traitor um alle anderen Spieler zu töten.
Der Jester gewinnt wenn er für mehr Kills verantwortlich ist als die Traitor. (Dies ist noch nicht bestätigt)
Die Traitor gewinnen, wenn Sie als letzter den Jester töten.(Der Jester wird zum Traitor, somit gibt es nurnoch Traitor. AUCH NOCH NICHT BESTÄTIGT)


@TimGoll , danke jedenfalls für den Tipp

**Comment by TimGoll** [comment]
![image](https://user-images.githubusercontent.com/13639408/74235852-3556a200-4cd0-11ea-807d-bb00b3d4ad32.png)

Klingt gut. Ich habe gerade den Jester komplett neu gemacht. Die Winstates sind jetzt deutlich klarer. Ich bin gerade im Code drin, falls du einen anderen Winstate willst, dann sag Bescheid. Dann mache ich das flott :D

**Comment by Paddy91088** [comment]
Es wäre praktisch wenn man einstellen kann , dass der Traitor den Jester töten darf, damit nur die Innocent den nachteil haben.

**Comment by TimGoll** [comment]
Es gibt `Respawn with killer role and killer dies, unless killer is serialkiller or traitor`

**Comment by Paddy91088** [comment]
ah das ist neu ! , sollte mal nen serverrestart machen dann sollte das ja dabei sein

**Comment by TimGoll** [comment]
ne, ist nicht neu. Ich habe es nur alles aufgeräumt. Wenn du die GitHub Version nutzt ja. Die Workshopversion wird geupdated wenn TTT2 0.6 rauskommt. Also in kürze, vllt am WE

**Comment by Paddy91088** [comment]
achso , okay , ja habe alles vom Workshop einbezogen

**Comment by Paddy91088** [comment]
dann warte ich gerne auf das kommende update , und ihr macht ürigends nen guten Job !

**Comment by TimGoll** [comment]
Danke! Wir geben uns Mühe :)
Ich schließe das mal, wenn dann doch noch was dazu einfällt, dann kannst du den Issue ja wieder öffnen oder uns einfach bei Discord schreiben,
