### ISSUE TITLE
New Role: Bonnie and Clyde

### ISSUE THREAD

**Issue by tobi-nb** [TTT-2/addon-ideas#25]
### Bonnie and Clyde

**Description:** Bonnie and Clyde is a new duo-role for 2 people. They can only spawn together. Due to their criminal history, Bonnie and Clyde will always have to play together and replace 2 existing traitors.

**Wincondition:** Both players survive and kill all other players (Bonnie and Clyde win) or one survives with the remaining traitors (normal traitor win) 

**Role Design:** They replace 2 traitors and will be displayed as one as well. Their main goal is to survive together. When one of them dies, the survivor of the duo can choose if he wants to sacrifice himself to respawn his teammate. If both survive until the end and there are only traitors remaining, they change sides and are revealed as Bonnie and Clyde. At this point their goal is to kill the traitors. If just one of them dies, their mission failed and the traitors win. 

**To discuss:** 

- What happens if just one survives? 
- I thought about mirroring the damage to both of them... Or something else to connect the two players
- I would like to have a sacrifice there, but I'm not sure yet what the profit of your teammates sacrifice should be...

**Why it might be fun to play:**
Bonnie and Clyde is a new concept, a duo role. You have to play together to reach your goals. And you have the chance to betray the traitors themselves...

**Comment by Alf21** [comment]
Moved to https://github.com/TTT-2/TTT2/discussions/762.
