### ISSUE TITLE
New Role: The Marshall (Detective)

### ISSUE THREAD

**Issue by Lunethia** [TTT-2/addon-ideas#26]
## The Marshall

**Description** The Marshall is a new subclass to the detective and he knows a lot about his fellow innocents. 

**Win condition and alignment** The Marshall wins with the innocents and is a part of the innocent team.

**Gameplay and Abilities** 

- The Marshall will spawn as a new detective subclass

- The Marshall has the ability to see innocents in the scoreboard

  - This only includes normal innocents and excludes any special innocent roles.

- The Marshall does not have a shop by default.

**Plays best with**

- Any special innocent addition

- Requires a lot of special innocents to not be broken

**Comment by Alf21** [comment]
Moved to https://github.com/TTT-2/TTT2/discussions/763.
