### ISSUE TITLE
New Role: The Diseased (Innocent)

### ISSUE THREAD

**Issue by Lunethia** [TTT-2/addon-ideas#27]
## The Diseased

**Description** The Diseased is an innocent that will spread his disease to his murderer.

**Win condition and alignment** The Diseased is part of the innocent team and wins with them.

**Gameplay and Abilities** 

- The Diseased will infect his murderer which takes half of his current HP and makes him also have the same disease if he is not part of team innocent.

- If the murderer dies the killer will have the same disease infecting them, taking half of his current Hp and this will go on until the round ends.

- If an innocent kills someone that is not part of team innocent and has the disease, their HP will be doubled. (However this innocent will also get the disease.) 

**Special interactions** (OPTIONAL)

- If a priest shoots an innocent with his holy deagle that has the disease the disease will be healed.

- If the priest shoots a non-innocent role with his holy deagle that has the disease that player will die. (Even if the priest shoots a traitor, and the priest won't die.)

**Comment by Alf21** [comment]
Moved to https://github.com/TTT-2/TTT2/discussions/764.
