### ISSUE TITLE
New Role: The Survivor (Own Team/Neutral Role)

### ISSUE THREAD

**Issue by Lunethia** [TTT-2/addon-ideas#28]
## The Survivor

**Description** The Survivor is just looking to live through the day. You may side with whoever you please in order to survive and win for only yourself???

**Win condition and alignment** The Survivor wins with any other winning faction and is not part of any team.

**Gameplay and Abilities** 

- The survivor starts with body armor of 50

- The survivor has a shop that only offers MORE body armor and a "Heal item", but he starts without credits. (idk what heal item rly)

- The survivor has a survive counter of some sort that tracks how many people have died already.

     - The survivor gets a credit for every third person that died. If the survivor was responsible for the deaths then they won't count.

     - If the survivor kills someone the survive counter (towards his next credit) will be reset/be subtracted by 1.

- The Survivor could be announced at round start??

- The survivor will win with any winning party, but take the win for himself???
(I'm unsure if the survivor should just "also win" (which in the current state of TTT2 won't be displayed and would be kind of boring) or steal the win from the original winning party without having to fight for it.)

**Comment by Alf21** [comment]
Moved to https://github.com/TTT-2/TTT2/discussions/765.
