### ISSUE TITLE
New Role: The Havoc

### ISSUE THREAD

**Issue by Lunethia** [TTT-2/addon-ideas#29]
## Havoc

**Description** Havoc is a new traitor that cleans up evidence of a murder.

**Win condition and alignment** Havoc wins with the traitors and is a part of their team.

**Gameplay and Abilities**

- If Havoc kills a player, the body will be automatically **cleaned**.

- If Havoc "confirms" an unidentified body, instead of identifying it, the body will be **cleaned**.

To all **cleaned** corpses the following applies if they are confirmed (by Havoc or anyone else)

- The **cleaned** corpse does not show who it was and what role the player had when confirmed.

- The information when inspecting erased and replaced with a single box that reads

     "This corpse was **cleaned** by Havoc"

- The player will be listed under alive or MIA respectively in the scoreboard even if confirmed

- Havoc does not have access to a shop.

**Additional Ideas**

- A HUD element, that tracks how many cleaned bodies have been found by players. Maybe including an icon with a number next to it.

**Interactions with other roles and items**

- Amnesiac: The Amnesiac should still be able to get a role from a **cleaned** body.

- Reviving roles such as:

- **Necromaner** A necromancer should be unable to revive a cleaned player.

- **Marker** The Marker should be unable to revive a cleaned player.

- ... Cleaned players cannot be revived.. we got it.

- A DNA Scanner cannot take DNA from a cleaned target.

**Comment by Alf21** [comment]
Moved to https://github.com/TTT-2/TTT2/discussions/766.
