### ISSUE TITLE
New Role: Whistleblower

### ISSUE THREAD

**Issue by h4ppy1337** [TTT-2/addon-ideas#3]
"I saw them. But they also saw me. What a pity for them, for they shall be outnumbered."

- The Spy is in the Traitor's team. He has a normal amount of 2 credits and his gameplay is like the one of a regular traitor.

- Additionally, the Spy has the ability to see most negative third-party roles by pressing tab. This includes any infected player, the Serialkiller, and the Jackal

- The Sidekick can't be found by the spy when being a Sidekick. However, when the Jackal dies and the sidekick appears to become the new Jackal, the spy can track him as usual.

- The costs of his spying powers are high. Although he can see most negative third party players by pressing tab, the players which he can track are also able to see his role in return by pressing tab. Still, the Traitors have the advantage of being a bigger group...

**Comment by Alf21** [comment]
Moved to https://github.com/TTT-2/TTT2/discussions/746.
