### ISSUE TITLE
New Role: Headhunter (Own Team/Neutral Killer)

### ISSUE THREAD

**Issue by Lunethia** [TTT-2/addon-ideas#30]
## The Headhunter

**Description** The Headhunter is a professional killer that is out to strike it rich through dirty, but necessary work.

**Win condition and alignment** The Headhunter is required to eliminate 2 non innocent players. The headhunter also has no alignment.

**Abilities and Gameplay**

- If the Headhunter kills an innocent he takes 50HP damage

- The Headhunter gets a Credit for every player that was not part of team innocent he kills. (It's his bounty to take!)

- The Headhunter has to survive till the end to win.

- The Headhunter starts without credits but with the shop of the traitors.

- The Headhunter has additional armor

- The Headhunter will always start with a rifle to strike from a distance.

**Comment by Lunethia** [comment]
A problem with this role is it's "way of winning".
As of right now, only one team can truly be declared "winner" of the round.
It would be cool to see changes to the current messages you get at a rounds end which give possibilities to see a multi-party victory.
This would make for amazing role concepts such as this one, that give a very different vibe to the otherwise rather stale gameplay. 
Additional ways of winning, by staying alive, or achieving your own objective could be very interesting to play around with. And would surely feel a lot better if you are actually seen as one of the winners at round end, which is currently not the case and would make a role such as this one pretty pointless and not as satisfying or fun to play.

**Comment by Alf21** [comment]
Moved to https://github.com/TTT-2/TTT2/discussions/767.
