### ISSUE TITLE
New Role: The Outsider (Neutral Role) 

### ISSUE THREAD

**Issue by Lunethia** [TTT-2/addon-ideas#31]
## The Outsider

**Description** The Outsider is a peculiar one, he never stuck with anyone and roams around doing what he pleases.

**Win condition and alignment** The outsider wins with any team that is not team innocent or team traitor. His alignment is therefor being a part of all non Traitor or innocent teams, he also wins alone if there are no custom teams left and all Ts and Innocents are dead.

*Abilities and Gameplay*

- The Outsider is able to see all roles of special teams in the scoreboard, and when looking at players. 

- All players of custom teams see the Outsiders role and can treat him as an ally if they so desire.

- The Outsider wins together with all custom teams. He should also be able to win alone if there are no custom teams spawned or alive in the current round.

- If there are only custom teams left, the Outsider can choose to turn against a team, or wait out the result.

- The Outsider does have a shop, but cannot generate credits (he can pick them up from corpses though)
  - If the Outsider has no custom team to ally with, because they either didn't spawn with him or died before he did, he will immediately receive 2 credits, but no way of gaining more. (exception as seen above)

**Comment by Pawel99UK** [comment]
this sound like a cooler type or the pirate role and more intressting

**Comment by Alf21** [comment]
Moved to https://github.com/TTT-2/TTT2/discussions/768.
