### ISSUE TITLE
New Faction: The Cult // New Cult Roles

### ISSUE THREAD

**Issue by Lunethia** [TTT-2/addon-ideas#32]
_A Cult has formed inside the Terrorist Oraganization! And they are out for power! Even though their ranks are still scattered adn their chain of command doesn't seem stable, can the Terrorists stop them, before the Cult manages to overpower any opposition?_

**It is highly recommended to make traitors be a secondary role with this addon(aka only letting one spawn). To make space for this faction to spawn if you are expecting to be playing with about 10 people or less.**

The Cult is planned to be a new faction for TTT2 that plays alongside the traitors and innocents and has the same goal as the traitors, be the last team standing and is an active threat to the innocents.
It is planned that most of them cannot see each other. To make them play more reserved and slow. And figure out who is friend or foe as they convert ever more members to their faction.

## The Cult (New Faction)

Here come certain specs of the faction itself.

- The Cult does not have a teamchat. 

- Very few Cult members should have access to the shop, special cult roles that do will come soon!

- Very few Cult members can see each other.

- The fact that the Cult is in an active round should be announced. Probably with an eventpopup and maybe with an additional sound.

- A Maximum of 2 Cult Members should spawn at round start. One being the Cult Leader, and another random cult member from the active cult pool on the server (default Cultist), this can however be adjusted with bigger groups to keep the Cult an active threat.

## The Cult Leader (Detective Like Cult Role)

- The Cult Leader will always spawn if the Cult Team enters the round. He is the main actor of this team.

- The Cult Leader will be able to generate new Cultist, probably using a sidekick deagle like weapon, that is on a timer after every shot, but can convert multiple times! (probably should introduce a max of some sort. Maybe 2. And a tremendous CD, even when missing, about 2 minutes?) 

- The Cult Leader can see all other active, or deceased members of the cult.

- The Cult Leader has no shop.

- The Cult Leader starts with some armor.

- Once the Cult Leader is dead all Cultists will follow him to the grave. (DOES NOT INCLUDE SPECIAL CULT ROLES)

## The Cultist (Base Cult Role)

- The Cultist is the base Cult role. It's the same as traitor or innocent, so to say.

- If multiple Cult members are spawning at round start, every Cult member that spawns after the first (which is always a Cult Leader) will be a Cultist. This can be overwritten with a different member of the Cult if there is a possibility for a different Cult member to spawn in play.

- The Cultist does not have a shop.

- The Cultist can only see the Cult Leader or Cult Adjutant as part of the Cult. (Like a Detective!)

## The Cult Assassin (Cult Subrole)

- The Cult Assassin can spawn as an additional Cult Member after the Cult Leader and replace a Cultist.

- The Cult Assassin has a wallhack.

- The Cult Assassin does not have a shop.

- The Cult Assassin can only see the Cult Leader or Cult Adjutant as their Teammates

## The Cult Ritualist (Cult Subrole)

- The Cult Ritualist can spawn as an additional Cult Member after the Cult Leader and replace a Cultist.

- The Cult Ritualist is able to revive one (maybe a convar) member of the Cult. This CAN be the Cult Leader.

- The Cult Ritualist has a special Radar that shows him all dead cult members, with their role colour as pings.

- The Cult Ritualist does not have a shop.

- The Cult Ritualist can only see the Cult Leader or Cult Adjutant as his teammate.

## The Cult Recruiter (Cult Subrole)

- The Cult Recruiter can spawn as an additional Cult Member after the Cult Leader and replace a Cultist.

- The Cult Recruiter can similar to the Cult Leader convert a player to the Cult.

- However he cannot convert a player right away. Since he will need to bide his time and wait for an opportunity to strike. After 2 minutes ingame time he can convert a single person to be a cultist. (the amount of time should be adjustable)

- The Cult Recruiter does not have a shop.

- The Cult Recruiter can only see the Cult Leader or Cult Adjutant as his teammate

## The Cult Zealot (Cult Subrole)

- The Cult Zealot  can spawn as an additional Cult Member after the Cult Leader and replace a Cultist.

- The Cult Zealot can rise to power and become a Cult Leader if the original Cult Leader dies, preventing a mass suicide within the Cult.

- The Cult Zealot does not have a shop

- The Cult Zealot starts with some armor

- The Cult Zealot can only see the Cult Leader or Cult Adjutant as his teammate.

## The Cult Adjutant (Cult Subrole)

- The Cult Adjutant can spawn as an additional Cult Member after the Cult Leader and replace a Cultist.

- The Cult Adjutant can be seen by any other Cult follower as a Teammate.

- The Cult Adjutant knows any other Cult member and sees them as a teammate.

## The Cult Adept (Cult Subrole)

- The Cult Adept can spawn as an additional Cult Member after the Cult Leader and replace a Cultist.

- The Adept has a shop available to them and starts with 2 credits. (the shop is the traitors)

- The Adept can only the the Cult Leader or Cult Adjutant as his Teammate

Obviously the Cult will only be viable in bigger games, or come at the cost of fewer traitors, as at least two of the Cult Members spawning at round start would be required for them to function as a faction and not just another new role.

Okay, to be extreeeeeeemely honest with you. If there were a possibility to replace traitors with this, I'd definitely choose to take action on that. Even if it ruins TTT's meta gameplay entirely. I'D LOVE TO DO IT!

**Comment by Lunethia** [comment]
All kinds of roles that I had in mind to be part of the faction have been written down. 
This is kind of ready to be coded now, I guess.
If there is anything unclear, let me know and I'd be more than glad to clarify it.

**Comment by Pawel99UK** [comment]
epic idea and hope that this will be added

**Comment by Alf21** [comment]
Moved to https://github.com/TTT-2/TTT2/discussions/769.
