### ISSUE TITLE
New Role: Crusader (Innocent)

### ISSUE THREAD

**Issue by Skatcat** [TTT-2/addon-ideas#33]
### Crusader:
**Basic description**

The Crusader wants to rid this world of heathens! But people can be heathens regardless of their faction… can the Crusader get rid of them and prevent evil from reigning at the same time?

**Gameplay**

The Crusader needs to kill all heathens. He is technically an innocent. If a Crusader spawns, a certain percentage of players in a game is marked as heathens, independent of their roles (Comparable to the Brotherhood). Only the Crusader (using the scoreboard or his crosshair) can identify heathens.

The Crusader needs to finish the game with all heathens dead to win. He cannot harm non-heathens.
Killing innocent heathens won’t cause the Crusader to lose karma.

To make it short: The Crusader needs to kill innocent heathens without being framed as evil and killed by the innocent team. On the other hand, he needs to avoid evil roles that aren’t heathens for it’s not his mission to eliminate them.

There can be multiple Crusaders but as with regular innocent roles, they don’t see the other Crusaders on the scoreboard. A Crusader can, obviously, never be a heathen.

**Win conditions**

The Crusader can win with the innocent team if all heathens are dead.

If all evil roles are dead, it’s up to him to quickly eliminate the last heathens so he can win with the innocent team.

If no heathens are alive but the innocent team hasn’t won yet, the Crusader has to wait for the other innocents to find the last evil players.

If all innocents are dead, the Crusader can only win if the last evil players are all heathens. If that’s not the case, he (and the innos) lose the round instantly for the Crusader can’t harm non-heathens.

If only a Crusader and a heathen Innocent are left, the Crusader, and by extension the innocent team, win if he takes out the last heathen, as the Crusader technically counts as an innocent himself.

**Why it might be interesting**

The Crusader is a role that’s unique in that he needs to kill people independent from their roles. This means that, even though he’s technically innocent, the heathen-status defines who’s his enemy which leads to many peculiar interactions.

Except for the Crusader, no role (exceptions below) can see heathens, so if he kills a heathen innocent, he will probably be labeled as an evil role. On the flipside, he can’t even kill evil roles who aren’t heathens so he has to be extra careful not to get taken out by them because he can’t defend himself.

Also, since the Crusader is innocent, if an Innocent kills him, they will lose Karma as it counts as killing a team mate (Because obviously it’s wrong to punish a murderer if it was religious murder -> logic!)
This might seem janky at first, but actually it might add some new depth to the game. If you out yourself as a Crusader, all teams might take advantage of you getting a ‘free pass’ for killing heathens, hoping, that the death of the heathens you kill could profit their own team.

Claiming you’re a Crusader is also feasible for evil roles to make the innocent team doubt themselves and not kill you immediately if you kill an innocent.

To add even more claim possibilities: Since the Crusader can’t harm non-heathens, he can demonstrate his inability to deal damage and claim he’s a Jester which might protect him from even further harm. On the flipside the Jester might claim he’s a Crusader and crash the party…

**Interactions with other roles**

If the Jester is a heathen, the Crusader can kill him without any repercussions.

Unknowns can be heathens too. In that case, when killed by the Crusader, they will normally respawn as another Crusader and become non-heathens.

A Priest can never be a heathen. Members of the Brotherhood can never be heathens and being added to the Brotherhood will revoke their heathen-status. The Crusader’s win condition is hereby automatically fulfilled if every heathen still alive gets converted to the Brotherhood. The Crusader can be part of the Brotherhood.

Getting revived and/or role-changed doesn’t revoke heathen-status, so even after turning traitor, a Wrath (for example) will stay heathen.

Occultists and Necromancers (+ their Zombies) are always heathens.

If a role that converts people to their team (Jackal, Infected etc.) is a heathen, the converted will be aswell.

Pirates giving their contract to a heathen will NOT become heathens themselves.

**Comment by Pythagorion** [comment]
The Karma Thing could be a problem. As far as I know, it isn´t possible to interact with the TTT Karmasystem by using Lua. Correct me if I´m wrong.

**Comment by Alf21** [comment]
Moved to https://github.com/TTT-2/TTT2/discussions/771.
