### ISSUE TITLE
New Role: The Guardian Angel (Neutral Role)

### ISSUE THREAD

**Issue by Lunethia** [TTT-2/addon-ideas#34]
## The Guardian Angel

**Description** The Guardian Angel is a divine being with the ability to bless a player of their choice!

**Win condition and alignment** The Guardian Angel starts off without a team or win condition. 
Once he spoke his blessing on a player he will win with that player.

**Abilities and Gameplay**

- The Guardian Angel is able to bless a player (similar to the pirate contract mechanic) of HIS choice.

- The blessed player will receive the Guardian Angels protection and can no longer take damage as long as the blessing is active.

- The blessing can only be broken by death.

- The Guardian Angel Will receive all and any damage that his blessed target player takes. This damage will be lowered by 50% (convar?). _The maximum amount of damage is capped by 25 per hit. So the Guardian Angel cannot die with less than 4 damaging hits on his blessed player. (if this appears to be literally impossible to implement just drop it lol)_ 

- The Guardian Angel will start with 50 armor.

- Damage taken through the blessing ignores the Guardian Angels armor.

- The Guardian Angel himself takes damage as normal.

- If the Guardian Angel dies so does the one he had a contract with (convar?).

- The Guardian Angel speaking his blessing will be announced to everyone.

- The Blessed player should be notified of this, either by a hud element or through a popup event.

- The Guardian Angel can see his targets team (convar).

- The Guardian Angel knows what team he is a part of.

- The protected target can see the Guardian Angel as a teammate (symbol above head, scoreboard).

- The Guardian Angel does not have access to any shop. (as to not buy any defensive/healing items, that'd be OP lol)

**Comment by Alf21** [comment]
Moved to https://github.com/TTT-2/TTT2/discussions/772.
