### ISSUE TITLE
New Role: The Detonator (Traitor)

### ISSUE THREAD

**Issue by Lunethia** [TTT-2/addon-ideas#35]
## The Detonator

**Description** The Detonator is a Traitor with expertise in mine-laying and explosives.

**Win condition and alignment** The Detonator is a Traitor and is part of Team traitor and wins with them.

**Abilities and Gameplay**

- The Detonator can see all other traitors and has the same perks as all other traitors usually have, such as a teamchat.

- The Detonator does have a shop, but starts without credits.

- The Detonator starts with three stickybombs which can be placed on bodies, living and dead alike.

- A placed sticky bomb will _somehow_ be shown to other members of the traitor team.

- If placed on a living player [LMB] the Detonator can activate all placed bombs on living players with [RMB], this will deal 150 damage in an area to them and others close enough to be hurt by it and counts as explosion damage.

- If placed on a dead body, the body itself becomes a mine, exploding once the next player touches it. "Being touched" means that the body is either interacted with using a magneto stick or alternatively, searched, confirmed, or stepped on by a player. This explosion will deal 150 damage to the one activating the bomb and count as explosion damage.

- The Detonator will receive 3[convar?] Bombs at round start.

- Placing the stickybombs may create a sound?

**Comment by Alf21** [comment]
Moved to https://github.com/TTT-2/TTT2/discussions/773.
