### ISSUE TITLE
New Role: The Bishop (Innocent)

### ISSUE THREAD

**Issue by Lunethia** [TTT-2/addon-ideas#36]
## The Bishop

**Description** The Bishop an innocent that is highly devoted to god and believes that everyone with the intention of redemption deserves a second chance in life.

**Win condition and alignment** The Bishop is part of the innocent team and wins with them.

**Abilities and Gameplay**

- The Bishop has the ability to grant a player other than himself a second chance. Once per round he can choose to mark a player which will be ressurected upon death, but only if the marked player is an innocent. 

- If the Bishop attempts to mark a Detective both the Detective and the Bishop take 50 HP damage.

- If the Bishop attempts to mark a Traitor, the Bishop dies.

- If the Bishop attempts to mark a role that is neither Innocent nor Traitor the Bishop dies, but that player still receives the Bishops mark.

- The Bishops mark also adds the player to the Brotherhood, if the marked player is an innocent.

- The Bishop can use his ability only once.

- The Bishop does not have a shop.

- The Bishops mark should be displayed on the left under passive perks.

**Interactions with other roles**

- The Bishop automatically joins the Brotherhood at round start if a priest is in the round.

- If the Bishop hits the Jester with his mark nothing happens, neither does the Bishop die nor does the Jester get the mark.

**Plays best with**

- The Priest

**Comment by Alf21** [comment]
Moved to https://github.com/TTT-2/TTT2/discussions/774.
