### ISSUE TITLE
New Role: The Watchman (Innocent)

### ISSUE THREAD

**Issue by Lunethia** [TTT-2/addon-ideas#37]
## The Watchman

**Description** The Watchman is an Innocent whose goal is to provide protection for his teammates.

**Win condition and alignment** The Watchman is an Innocent and wins with them.

**Abilities and Gameplay**

- The watchman shares the perks and restrictions of a normal innocent.

- The watchmans specialty is his proficiency in guarding himself and his teammates, he is able to give other players armor.

- The Watchman starts with 30 armor.

- The Watchman can give up to 2 [convar?] other players an armor value of 30. (normal armor item)

- The Watchman does so by applying his armor [ITEM] (would propaply need something visual idk) on other players in melee range. This player can be innocent or traitor, whoever the watchman trusts the most.

- The Watchman cannot provide armor to the same person twice.

- The Watchman cannot provide armor to Detectives

**Comment by Alf21** [comment]
Moved to https://github.com/TTT-2/TTT2/discussions/775.
