### ISSUE TITLE
New Role: The Bard (Innocent)

### ISSUE THREAD

**Issue by Lunethia** [TTT-2/addon-ideas#38]
## The Bard

**Description** The Bard is an Innocent that likes to sing and entertain.

**Win condition and alignment** The Bard is an Innocent and wins with the Innocents.

**Ability and Gameplay**

- The Bard plays as a normal innocent and has the regular innocent features.

- The Bard does not have a shop.

- The Bard has the ability to sing about the player that killed him when he dies.

- If the Bard is killed an event popup will announce the Bards tragic death as well as the Role of his Killer. 
- The Bard will automatically be confirmed for everyone upon dying without anyone having confirmed him.

**Comment by Alf21** [comment]
Moved to https://github.com/TTT-2/TTT2/discussions/776.
