### ISSUE TITLE
New Role: The Beggar (Neutral Role)

### ISSUE THREAD

**Issue by Lunethia** [TTT-2/addon-ideas#39]
## The Beggar

**Description** He is a person in need and happy to receive any gift he can get.

**Win condition and alignment** You may change your role to that of another player and take on their win condition and alignment.

**Gameplay and Abilities**

- The Beggar starts without a team and cannot win by roundstart.

- If the beggar picks up a dropped Shopitem he will take on the role of the one dropping it to him.

- Anyone with a shop will be able to see who the Beggar is.

**Plays well with**

- Survivalist

- Serial Killer

- Necromancer

- Jackal

**Comment by Alf21** [comment]
Moved to https://github.com/TTT-2/TTT2/discussions/777.
