### ISSUE TITLE
New Role: The Mercenary(Neutral Role)

### ISSUE THREAD

**Issue by Lunethia** [TTT-2/addon-ideas#40]
## The Mercenary

**Description** The Mercenary is here to strike a deal, a big one at that. The highest bidder may get his competent assistence in their fight for dominance.

**Win condition and alignment** You may change your team to that of another player and take on their win condition and alignment.

**Abilities and Gameplay**

- The Mercenary starts off as a neutral role, that can be influenced by one thing only, currency. Money rules the world and he is out to get lots of it. Money, is credits, btw, for everyone who didn't get it yet.

- The Mercenary will be seen as such by anyone that has a shop with the ability to get credits. Either at round start or during the round.

- Every player that has a credit to spare, may decide to give it to the Mercenary. The Team that gives the Mercenary the most credits within the first minute of the round may be his contractor.

- If there is a tie between potential contractors or no one willing to pay the mercenary at all the mercanary will become his own team and strike anyone down that is in his way. Ignorance and unwillingness to pay him a LOT shall not be accepted, it was a waste of time anway.

- In any case will the mercenary take every credit anyone gives to him, regardless whether a contract will be formed or not, look at it as an advance payment to create some trust.. 

- If the Mercenary takes a side and joins a team, the fact will only be announced to the mercenary himself. No one will know who the mercenary joined, if at all. Well, they will know when the mercenary strikes them down cold to the ground.

- The Mercanary has a shop of his own to give his freshly earned credits a good use and should have access to any item on the server, this includes detective items, you never know which side he ultimately end up on.

**Plays well with**

- Survivalist
- Hitman
- Serial Killer
- Jackal
- Necromancer

**Comment by Alf21** [comment]
Moved to https://github.com/TTT-2/TTT2/discussions/778.
