### ISSUE TITLE
New Role: The Hypocrite (Innocent)

### ISSUE THREAD

**Issue by Lunethia** [TTT-2/addon-ideas#41]
## The Hypocrite

**Description** They have always shown themselves to be loyal, but in reality do they not really value the currrent system, still are they bound by their superiors, until..

**Win condition and alignment** The Hypocrite plays in the innocent team and wins with them.

**Abilities and gameplay**

- The Hypocrite is a part of the Innocent team at roundstart but can change to being a traitor during the round.

- The Hypocrite cannot spawn without detectives in the round.

- If all detectives are dead (maybe for 10 seconds in case of a Second Chance in play) the Hypocrite will be changed into a Traitor and frorm that point onwards play and win in the Traitors team.

**Comment by Alf21** [comment]
Moved to https://github.com/TTT-2/TTT2/discussions/779.
