### ISSUE TITLE
New Role: The Overloader (Traitor)

### ISSUE THREAD

**Issue by Lunethia** [TTT-2/addon-ideas#42]
## The Overloader

**Description** The Overloader is a skilled hacker here to ruin the day for every innocent in town.

**Win condition and alignment** You are a Traitor and win with team Traitor.

**Abilities and Gameplay**

- The Overloader has hacked everyones smart devices, as a result no one is able to use their shop! No one but the traitors may access their shops until the Overloader has died.

- The Overloader does not have a Shop himself.

- All other Traitors that have access to the traitor shop may shop as per usual.

**Comment by Pythagorion** [comment]
Funny. I was thinking about such a role some time ago, with the same functions. But I am not sure if it's possible to block the access to shops.

**Comment by Lunethia** [comment]
It sounded like an interesting idea to me, so I wrote it down for later. Just in case ;)
But I have no idea if any of this is possible. haha.

**Comment by Alf21** [comment]
Moved to https://github.com/TTT-2/TTT2/discussions/780.
