### ISSUE TITLE
New Role: The Staller (Traitor)

### ISSUE THREAD

**Issue by Lunethia** [TTT-2/addon-ideas#43]
## The Staller

**Description** The Staller is a Hacker that got into the terrorists information network and sabotaged it as a result.

**Win condition and alignment** The Staller is a Traitor and wins with team Traitor.

**Abilities and Gameplay**

- As long as the Staller is alive, confirmation of dead bodies will be delayed, which also means, that access to a dead players identity, role and insight on additional information regarding the body will be blocked.

- Every confirmed body will remain unconfirmed even if a confirmation action is done by a player. The confirmation will be held back as long as the Staller is alive.

- If the Staller dies every confirmed body will then be revealed as confirmed. 

- Traitors will still be able to search a dead body covertly.

- Credits can still be withdrawn by everyone with a shop and access to the credit withdrawel feature. (Can this even be blocked?)

- The Staller does have a shop and starts with one credit.

**Comment by Alf21** [comment]
Moved to https://github.com/TTT-2/TTT2/discussions/781.
