### ISSUE TITLE
New Role: The Joker (Innocent Role)

### ISSUE THREAD

**Issue by Lunethia** [TTT-2/addon-ideas#44]
## The Joker

**Description** The Joker has always been that ace that you keep until the very end. He is there to change the tide of the battle in an instant, if need be.

**Win condition and alignment** The Joker starts off as an innocent and wins with the innocents.

**Abilities and Gameplay**

- The Joker will start off as a regular innocent. He will not know that he is the Joker.

- The Joker will be activated through 2 different possible triggers.

1. If the Joker is alive and the game enters the "Overtime" phase, the Joker will receive his actual role.
2. If the Joker is alive and he is the last innocent alive, then the Joker will receive his actual role.

- If the Joker died before one of the two scenarios have taken effect he will remain dead and no one will ever know of his true potential.

- Once the Joker is revealed he will receive a shop, three credits and 30 armor.

**Comment by Gensokian** [comment]
Seems interesting; I'll give it a shot
Totally not gonna think about adding some sort of persona reference.

**Comment by Alf21** [comment]
Moved to https://github.com/TTT-2/TTT2/discussions/782.
