### ISSUE TITLE
New Role: Kefauver (Traitor)

### ISSUE THREAD

**Issue by Lunethia** [TTT-2/addon-ideas#45]
## Kefauver

**Description** You're a traitor and your plan is to leave everyone suspended in fear!

**Win condition and alignment** You are a Traitor and win with Team Traitor.

**Abilities and Gameplay**

- Once per game you can decide to reveal the entire Traitor Team to everyone. This means that the names of all traitors are openly revealed to everyone. This is to instill fear into your enemies and show them that the traitors don't fear anyone.

- If Kefauver activates his ability every Traitor will receive 2 Credits and 30 armor and be fully healed to 100HP immediately in exchange for being revealed. Éveryone fear the traitors might!

**Comment by Alf21** [comment]
Moved to https://github.com/TTT-2/TTT2/discussions/783.
