### ISSUE TITLE
New Role: The Imposter (Neutral Killer)

### ISSUE THREAD

**Issue by Lunethia** [TTT-2/addon-ideas#46]
## The Imposter

**Description** You are an inspired imitator of the traitors work. You would give anything to be like them, yet they wouldn't take you into their ranks. Now you are seeking revenge while wearing their name.

**Win condition and alignment** The Imposter has to kill everyone that opposes him. He may spare anyone else.

**Abilities and Gameplay**

- The Imposter will be confirmed as a Traitor.

- The Imposter will be seen as a Traitor for other Traitors.

- The Imposter does not know who the Traitors are though.

- The Imposter has his own shop and starts with 2 credits.

- The Imposter is basically an evil spy. :p

**Comment by AlessandroLevante** [comment]
I didn't understand something completely, should they kill traitors too or only innocents and neutral players?

**Comment by Pawel99UK** [comment]
had the same idea u now me saying the double agent

**Comment by Alf21** [comment]
Moved to https://github.com/TTT-2/TTT2/discussions/784.
