### ISSUE TITLE
New Role: Shaman (Traitor)

### ISSUE THREAD

**Issue by Skatcat** [TTT-2/addon-ideas#47]
### Shaman;
**Basic description**
The Shaman uses the power of projection to rid himself of the innocents without being in danger himself. His body, however, stays behind...

**Gameplay**
The Shaman is a Traitor who does not possess a shop, akin to the Vampire. However, he possesses the power of **Spirit Projection.**

_Spirit Projection_
This is the passive ability of the Shaman and is activated using the **transformation** key.

Using Projection will create a spiritual doppelganger controlled by the Shaman while his original body stays behind in a holstered pose.

Controlling the Projection is pretty straightforward: You can move around, use and interact with everything like you normally could.

By pressing transformation again, you can call back the Projection and return to your original body immediately. The ability will be on a cooldown (def. 60 seconds). It will also be on cooldown if your Projection gets destroyed.

The Projection can damage and kill players normally. While the Projection takes regular damage and will be destroyed after having taken enough damage itself, only a fraction of this damage will be transfered to the original body, however killing the Projection will NEVER be able to kill the original body, only get him down to 1 HP.

The Projection's base HP is always whatever the Shaman's current HP is. If you are at 50 HP and project, your projection will spawn with 50 HP for example. By default, the main body will receive 1/5 of whatever damage the projection receives.

The Projection will still show the Shaman's name normally when looked at. Visually, there is no difference between the Projection and the Shaman himself for other players.

When the Projection gets called back, it will simply vanish without an effect or a sound, allowing for stealth / confusion plays. If it gets destroyed, a sound effect and a little bit of smoke will appear. It drops no corpse.

The Projection will NEVER appear on radars. Only the Shaman's original body will.

**Win conditions**
The Shaman is a traitor and thus wins with the traitor team.

**Why it might be interesting**
There aren't many traitor roles and having another one similar to the Vampire where the shop is replaced with a unique transformation gimmick seemed interesting to me.

Furthermore, the projection ability gives room for a multitude of fun plays like making the projection vanish to seemingly be at multiple places at the same time., try to be considered proven because you 'weren't at the site of the murder' etc.

**Interactions with other roles**
The Detective's DNA scanner is ineffective against the projection: It will never leave DNA.

Since the Projection can hold onto items, it CAN pick up the Pirate's contract.

It CANNOT be: Hit by the Jackal's deagle or turned into an Infected.
If the Jackal hits the projection with the sidekick deagle, nothing happens. The Infected can destroy the projection but it will not spawn an infected.

If the Priest hits the projection with a holy deagle, it will be destroyed instantly with no repercussions for the Shaman except being in cooldown.

The Marker cannot mark the projection.

**Comment by Alf21** [comment]
Moved to https://github.com/TTT-2/TTT2/discussions/785.
