### ISSUE TITLE
Additional detective alignments!! (Detective)

### ISSUE THREAD

**Issue by Lunethia** [TTT-2/addon-ideas#49]
**Additional Detective alignments for TTT2**

This Issue looks to implement Detectives that will not belong to the innocent team!
Regardless of which faction they support, they will always look like the good ol' regular detective!

Traitor Detective: This Detective is secretly siding with the traitors!

Chaotic Detective: This Detective is secretly it's own team!

Psycho Detective: This Detective is secretly part of the Serial Killers team! (only spawns with serial killer)

Undead Detective: The Detective is secretly part of the Infecteds team, and dies if the infected is killed!

Holy Detective: The Detective is part of the Innocent team, but starts as a member of the brotherhood! Can only spawn if there is a priest!

**Comment by kingYarok** [comment]
Here are some name suggestions.
Traitor Detective = Turncoat
Chaotic/Outcast Detective = Deceiver
Serialkiller/Psychotic Detective = Savage
Undead/Infected/Necromancer Detective = Possesed Prosecutor

**Comment by Lunethia** [comment]
Okay, I think I'll rearrange that a bit. A real fan of deceiver!

Traitor Dete = Infiltrator
Neutral Detective = Deceiver
SK Dete = Psychopath
Infected dete = Lich
Holy dete = Saint

**Comment by Alf21** [comment]
Moved to https://github.com/TTT-2/TTT2/discussions/788.
