### ISSUE TITLE
New Role: Deathhunter

### ISSUE THREAD

**Issue by TimGoll** [TTT-2/addon-ideas#5]
Spawns with a special gun, the deathhunter gun
Plays as innocent player
The gun deals no demage, but it links a player with the deathhunter
Maybe the other player knows that he is connected with an other player (like the deathgrip in TTT Totem)
If the deathhunter dies, the other player dies (or gets damage) too
The link breaks if only two players are still alive

**Comment by Alf21** [comment]
Moved to https://github.com/TTT-2/TTT2/discussions/749.
