### ISSUE TITLE
New Role: The Deputy (innocent)

### ISSUE THREAD

**Issue by Molderrm** [TTT-2/addon-ideas#50]
Role: a mini detective but can switch sides if the opportunity presents itself.

Win condition: If still a innocent by the time the game is over, then they win as an innocent. If they turn traitor they win by killing the other innocents.

Abilities: Can investigate bodies, like a detective but can switch to the traitors but can switch sides if the player so chooses.

Once they switch the traitor they cant switch back.

Will loose karma, and some health if you kill an innocent deputy while killing a traitorous one will have no penalty.

**Comment by Histalek** [comment]
Keep in mind that there is already a Deputy role (ref: https://docs.ttt2.neoxult.de/features/roles/)
