### ISSUE TITLE
New Role: The Juggernaut (Neutral Killer)

### ISSUE THREAD

**Issue by Lunethia** [TTT-2/addon-ideas#51]
## The Juggernaut

**Description** You're a heavily armored killer looking for revenge on the terrorists that took everything from you.

**Win condition and alignment** You have to kill every terrorist, innocent and traitorous as well as all other killers in order to win, you may spare anyone else.

**Abilities and Gameplay**

- The Juggernaut will start with 50 points of armor.

- The Juggernaut will start with 20 + 10 additional HP for each other player in the game at the start of the round.

-> 5 other players (6 player game) 
-> The Juggernaut starts with 100 HP +20 HP +10x5 HP = 170 HP

- The Juggernaut does not have a shop by default.

- It might be wise to give the Juggernaut a Radar to locate his foes by default. A last evil player without radar can stretch the rounds unnecessarily.

**Comment by Pawel99UK** [comment]
yes this is a great idea

**Comment by PROFI5** [comment]
thats a real nice role

**Comment by Alf21** [comment]
Moved to https://github.com/TTT-2/TTT2/discussions/789.
