### ISSUE TITLE
New Role : Accomplice(Traitor)

### ISSUE THREAD

**Issue by westooooo** [TTT-2/addon-ideas#52]
**[Role Info]**

・The Accomplice is  is a Traitor working together with the other traitors with the goal to kill all other non-traitor players.
・The Traitor can see who is the Accomplice.
・But The Accomplice can't see who is the Traitor.
・The Accomplice can't win alone.
・To explain it in werewolf game, The Mad man.
・He can't pick up credits from body with credits.

**Comment by TimGoll** [comment]
Looks interesting. However I'm a bit confused why you opened a role idea if you're already working at it by yourself. 

If you need help with specific things, feel free to ask on our discord

**Comment by westooooo** [comment]
sorry, TimGoll. You don't have to worry about that.

**Comment by PROFI5** [comment]
why did u close it?

**Comment by TimGoll** [comment]
Because he created the role by himself

**Comment by westooooo** [comment]
yes, I'm sorry
