### ISSUE TITLE
New Role: The Swapper (Neutral Role)

### ISSUE THREAD

**Issue by SmungDaal** [TTT-2/addon-ideas#53]
**Description**: The Swapper is a role that plays like the Jester (can't deal damage, and wants others to kill them), except once someone kills the Swapper, both the Swapper and their murderer revive, but their roles are swapped.

**Win Condition**: The Swapper cannot win. The goal of The Swapper is to pass their role onto someone else.

Long story short, The Swapper is the same thing as The Swapper from the TTT1 [Custom Roles](https://steamcommunity.com/sharedfiles/filedetails/?id=1215502383) mod along with [this](https://steamcommunity.com/sharedfiles/filedetails/?id=2112620831). It's the only role that Custom Roles has that TTT2 doesn't, so someone making a Swapper for TTT2 would be great.

**Comment by PROFI5** [comment]
gets the killer revived too?

**Comment by SmungDaal** [comment]
Yes! They swap roles after they both revive.
This creates a fun game of tag, since after you kill the Swapper, you become the Swapper, and now your goal is to get someone else to swap with you as well.

**Comment by PROFI5** [comment]
will the bad guys know that hes a swapper or only as jester? oh and is infected allowed to kill him?

**Comment by SmungDaal** [comment]
It would work as the Jester does so yes. All Traitors and Third Party Killer roles would know that he is a Swapper, and would Swap roles with him after killing him

**Comment by SmungDaal** [comment]
And for example, if the main Infected killed the Swapper, they would both die, all other infected will die because of this, and the Swapper will come back as the Infected and the old Infected respawns as the Swapper

**Comment by PROFI5** [comment]
but shouldnt the infected then know hes a swapper?

**Comment by SmungDaal** [comment]
They would know, I meant to imply that he killed the Swapper on accident, knowing they were the Swapper. Sorry if I worded it weirdly.

**Comment by PROFI5** [comment]
ok

**Comment by Alf21** [comment]
Moved to https://github.com/TTT-2/TTT2/discussions/790.
