### ISSUE TITLE
New usefull HUD component 

### ISSUE THREAD

**Issue by ThePlatinumGhost** [TTT-2/addon-ideas#55]
I would advice a new-userfriendly hud component like this in old_ttt hud
![image](https://user-images.githubusercontent.com/36534723/96644578-8fad0580-1329-11eb-8c5e-b8bb1f2487c4.png)
also in the others HUD in the bottom-left
**I known** is present on top on other HUD
![image](https://user-images.githubusercontent.com/36534723/96644776-d438a100-1329-11eb-9c27-eb7620bc4412.png)
but for the new user that are approcing the gamemode is more friendly on bottom-left, and maybe with the Name of TEAM for example
in this case TEAM INNOCENT
![image](https://user-images.githubusercontent.com/36534723/96645476-e5ce7880-132a-11eb-9ccc-b13971185bb0.png)
(Concept idea made with paint XD)
this may be super-usefull for role like Pirate, Bodyguard and also for the new players approcing TTT2
Because i noticed that new user tend to ignore the icon on the top, also because the don't known what's mean the icon and don't get the team right

PS: the bloodlust or the target of hitman could be moved above this bar

**Comment by Alf21** [comment]
Moved to https://github.com/TTT-2/TTT2/discussions/793.
