### ISSUE TITLE
New Role: Private Investigator

### ISSUE THREAD

**Issue by CptHaxray** [TTT-2/addon-ideas#57]
Note: I'm taking very heavy inspiration from a similar role idea suggested a while ago, The Reaper. 

**Team:** **Innocent**

**Description:**
An innocent role. They start the round unable to talk to anyone(be it over the microphone or in chat). They also deal massively reduced damage by default. They start with a Radar showing them the location of all unided dead bodies(identified bodies will not appear). 
Upon iding a body, they are alerted to the Killer's Role and name. If the Killer was not on the Innocent Team, they gain a faster pinging radar that tracks the killer. They gain a damage boost(Not sure of exact amount, likely a convar adjustable option) against the murderer. The Murderer is alerted to the fact a Private Investigator is now chasing them. 
If someone else kills their target, they have to find a new Unided body again. If they successfully manage to kill their target, they will copy the role of the Victim(But will remain on the Innocent team) and gain the ability to speak again, but lose the body Radar.

Additionally, if the Dead body of a Private Investigator is found, they will display as a random non-innocent role. 

Essentially an innocent role who is uniquely powerful by virtue of being able to instantly figure out the identity of any non-innocent aligned killer, but lacks any ability to share this knowledge to the rest of the team and has to take action on their own. Due to both their damage penalties and lack of being able to communicate, they will have to be smart about trying to take down the killer. It is important they can't be confirmed as a Private Investigator when killed to avoid being an instant confirmation of the Private Investigator's target as being an evil roles.

To clarify the "Remain on innocent team but copies the role of the Victim', they will obtain the victim's role(be it an Innocent, a Detective, or something not normally on the Innocent team like a Traitor or Jackal), but their team will remain Innocent despite their role's normal alignment, similar to how the Doppleganger role stays on the Doppleganger team despite taking another role.

**Comment by Alf21** [comment]
Moved to https://github.com/TTT-2/TTT2/discussions/794.
