### ISSUE TITLE
New Role: Arsonist

### ISSUE THREAD

**Issue by Skatcat** [TTT-2/addon-ideas#7]
### **Arsonist**
**Description**

The Arsonist is an evil role. His goal is to kill everybody. But he can’t do so by regular means… He needs to burn his victims to feel an ounce of satisfaction.

**Role abilities**

The Arsonist is immune to fire and, by nature, has a 50% bullet resistance. On the flip side: He deals no damage! Then, how does he kill?! 

Easy: He must find people and press “E” on them to douse them in gasoline. This process does not emit sounds or alert the victim in any way. By using his special weapon, the lighter, he can incinerate everybody on the map he has doused before. The incinerated people face certain death.

Doused people are marked on the Arsonist’s scoreboard.

Once the Arsonist has incinerated a certain amount of people and is satisfied, his abilities slowly grow stronger. When he incinerates people, his strength comes back. To deal 100% damage like any other player, he’d have to douse and incinerate at least 1/3 of all players. This means: The earlier an Arsonist is found, the better for everyone else. 

_Optional_
In games with few players, a ConVar should exist to remove the latter mechanic and make the Arsonist always deal no damage, no matter what. This forces him to incinerate everybody with his lighter.
There could also be an option to decide how much ammo the lighter has, i. e. how often the Arsonist can incinerate people.

**Win conditions**

To win, the Arsonist must be the last one standing. 

**Why it might be interesting**

This adds another no-damage role, next to the Jester, only this time around the Arsonist is someone you definitely want to kill. This makes the interactions with both roles a bit deeper.

He’s also unique in a way where he actively seeks the proximity of everybody so he can douse them with E. The Arsonist must find ways to be in close range to everyone without seeming suspicious.

**Interactions with other roles**

When it becomes clear, that the Arso deals no damage, he’ll be quickly prioritized by Traitors, which means that he must find balance between being close to other players but also keeping his abilities secret.
In general, the Arso should stay within crowds for the first part of his game, so he can douse as many people as possible without getting picked off by an evil role.

**Comment by Alf21** [comment]
Moved to https://github.com/TTT-2/TTT2/discussions/750.
