### ISSUE TITLE
New Role: Possessed

### ISSUE THREAD

**Issue by Skatcat** [TTT-2/addon-ideas#8]
### **Possessed**

**Basic mechanics**

The Possessed is an evil role. On the surface, he seems like a regular, harmless guy. But once his inner demon awakens… no one can stop him.

**Role abilities**

The Possessed starts off as a regular player without any special powers. However, after a certain amount of time (default: 3 minutes?) the demon he’s possessed by takes over and turns him into a powerful fiend with increased HP, damage, speed and damage resistances across the board.

However, the Possessed isn’t entirely happy with this destiny and seeks to redeem himself. If he kills anyone before turning into a demon, he dies of guilt immediately. 

Also, the process of turning into a demon isn’t without its hardships. In set intervals, the Possessed will emit sounds (Demonic laughter? Screams?) that hint at his transformation. This means that he can’t always stay close to people without being found out. The sounds aren’t loud enough to prevent him from staying near people at all times but should at least force him to be in a lonely corner for a couple of seconds.

**Win conditions**

For the Possessed to win, he needs to turn evil and kill everyone in his path.

This is a twist compared to other evil roles: When other evil roles and traitors are eliminated, the round ends, similar to the Jester. This means that the unturned Possessed is ‘saved’. He doesn’t get any points, but at the end of the day, the round ends before he could do any harm.

**Why it might be interesting**

Similar to the Arsonist role suggestion, this evil role is a bit unorthodox. There’s a big payoff in his transformation, but he must play very carefully, avoiding the proximity of other players to get there.

The role is extremely volatile: Until your transformation, you need to be careful, as not to arouse any suspicion, but you also can’t defend yourself without dying yourself.

Also his win conditions are unique for an evil role, since he can only win if the round doesn't go on too long. So the Possessed can decide: Do you want the round to go by without much blood shed? Or do you want to protect other evil roles to extend the round, just so you can transform?

**Interactions with other roles**

To most roles, he just acts like a regular evil role you want to get rid of.

When the Unknown gets killed by the turned Possessed, he immediately becomes one as well. Watch out for these demons duking it out!

[Only with Priest] If the Priest suggestion is taken into consideration, the Holy Deagle could cure the unturned Possessed and 1-shot kill the turned Possessed.

**Comment by Alf21** [comment]
Moved to https://github.com/TTT-2/TTT2/discussions/751.
